<a href="https://colab.research.google.com/github/Neha198996/heroku/blob/master/Copy_of_Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow_text

In [ ]:
import tensorflow
import tensorflow_hub as hub
import tensorflow_text as text
hub_preprocess_url='https://kaggle.com/models/tensorflow/bert/frameworks/TensorFlow2/variations/en-cased-preprocess/versions/3'
hub_encoder_url='https://www.kaggle.com/models/tensorflow/bert/frameworks/TensorFlow2/variations/en-cased-l-12-h-768-a-12/versions/4'
bert_preprocesses=hub.KerasLayer(hub_preprocess_url)
bert_encoder=hub.KerasLayer(hub_encoder_url)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import nltk
from nltk.corpus import stopwords
import string
from nltk.stem import WordNetLemmatizer
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')
import sklearn

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
sw=stopwords.words('english')
sw

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
lemma=WordNetLemmatizer()

In [ ]:
df=pd.read_csv('/content/airline.csv',encoding='latin')


In [ ]:
df_New=df[['airline_sentiment','text']]
df_New

airline_sentiment                                               text
0              neutral                @VirginAmerica What @dhepburn said.
1             positive  @VirginAmerica plus you've added commercials t...
2              neutral  @VirginAmerica I didn't today... Must mean I n...
3             negative  @VirginAmerica it's really aggressive to blast...
4             negative  @VirginAmerica and it's a really big bad thing...
...                ...                                                ...
1036          positive  @united flight 1491...plane from SFO to DEN is...
1037          positive  @united thanks. Just a program comment; the sy...
1038          negative  @united 20 min more delays to flt 2086 at sfo ...
1039          negative  @united Heads up We didn't check 8 bags, 2 we ...
1040          negative  @united This must be a drone ‰ÛÏ@united: @...

[1041 rows x 2 columns]

In [ ]:
df_New['text']=df_New['text'].apply(lambda x:x.lower())


<ipython-input-8-24ef87de3334>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_New['text']=df_New['text'].apply(lambda x:x.lower())


In [ ]:
def Y_test(x):
    if x=='negative' :
        return 0
    elif x=='neutral':
        return 1
    else:
        return 2

In [ ]:
df_New_X=df_New[['text']]
df_New_Y=df_New['airline_sentiment'].apply(lambda x: Y_test(x))
df_New_Y=pd.DataFrame(df_New_Y)
df_New_Y

airline_sentiment
0                     1
1                     2
2                     1
3                     0
4                     0
...                 ...
1036                  2
1037                  2
1038                  0
1039                  0
1040                  0

[1041 rows x 1 columns]

In [ ]:
df_New_X['text']=df_New_X['text'].apply(lambda x:' '.join([word for word in x.split() if word not in sw]))
df_New_X['text']=df_New_X['text'].apply(lambda x:' '.join(word for word in nltk.word_tokenize(x) if word not in string.punctuation))
df_New_X['text']=df_New_X['text'].apply(lambda x:' '.join(word for word in nltk.word_tokenize(x) if word not in 'virginamerica'))
df_New_X['text']=df_New_X['text'].apply(lambda x:' '.join(lemma.lemmatize(word,pos='v') for word in nltk.word_tokenize(x)))

<ipython-input-11-96d05d577d98>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_New_X['text']=df_New_X['text'].apply(lambda x:' '.join([word for word in x.split() if word not in sw]))
<ipython-input-11-96d05d577d98>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_New_X['text']=df_New_X['text'].apply(lambda x:' '.join(word for word in nltk.word_tokenize(x) if word not in string.punctuation))
<ipython-input-11-96d05d577d98>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice f

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(df_New_X,df_New_Y,test_size=0.2,random_state=101)

In [ ]:
X_train

text
23   make bos gt las non stop permanently anytime soon
399    seat 4c can not even open laptop pay extra seat
368  flight vx399 head la jfk dirtiest va plane eve...
980                        unite think dm would better
123  thank outstanding nyc-jfk crew move mountains ...
..                                                 ...
575  unite addition first flight delay hour 'm arri...
973  unite premier gold desk change flight waive fe...
75       awesome fly yall sit morning way correct bill
599                   unite last night 's 1235/ord-lga
863  unite send email bad experience send back gene...

[832 rows x 1 columns]

In [ ]:
import tensorflow as tf
preprocessed_tex=bert_preprocesses(X_train.text)

In [ ]:
preprocessed_text_test=bert_preprocesses(X_test.text)

In [ ]:
bert_model=hub.KerasLayer(hub_encoder_url)

In [ ]:
bert_results=bert_model(preprocessed_tex)
bert_results.keys()

dict_keys(['encoder_outputs', 'sequence_output', 'pooled_output', 'default'])

In [ ]:
bert_results_test=bert_model(preprocessed_text_test)

In [ ]:
from tensorflow.keras.layers import Dense,Dropout,LSTM
from tensorflow.keras import models, layers, optimizers,losses
from tensorflow.keras.models import Sequential
model=Sequential()

In [ ]:
#model.add(LSTM(100,dtype='float32'))
model.add(Dense(10,activation='relu'))
#model.add(Dense(10,activation='tanh'))

In [ ]:
#model.add(Dropout(0.2))
model.add(Dense(3,activation='softmax'))

In [ ]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics='precision')

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

In [ ]:
bert_results_test

{'encoder_outputs': [<tf.Tensor: shape=(209, 128, 768), dtype=float32, numpy=
  array([[[ 0.2720374 , -0.0153297 , -0.07035643, ...,  0.06718507,
            0.02377379, -0.1687272 ],
          [-1.8127695 ,  1.0553179 , -1.0874697 , ..., -0.83940387,
            0.02637151,  0.85017717],
          [-0.22143191,  1.1769894 ,  0.18475626, ...,  0.16185735,
            0.25265244,  0.10771801],
          ...,
          [-0.5664349 ,  0.23795989,  0.17067873, ..., -0.03267615,
           -0.2515175 ,  0.01995324],
          [-0.7256158 ,  0.08134431,  0.03407162, ..., -0.10646334,
           -0.09683032,  0.25847474],
          [-0.47412425,  0.45958796,  0.12880689, ..., -0.38792807,
           -0.08201817,  0.24558285]],
  
         [[ 0.281141  , -0.04980342, -0.12235946, ...,  0.01471268,
            0.00863682, -0.10879304],
          [-1.1744655 , -0.11312156, -1.2847077 , ..., -0.4030109 ,
           -0.65649414,  0.67812824],
          [ 0.7577983 ,  0.2622866 , -0.13600485, ..., 

In [ ]:
(np.array(bert_results['pooled_output']))

array([[-0.7207351 ,  0.49164957,  0.99984807, ...,  0.9999615 ,
        -0.8670166 ,  0.9931306 ],
       [-0.7167349 ,  0.506276  ,  0.9999472 , ...,  0.9999756 ,
        -0.6101237 ,  0.99171144],
       [-0.70682144,  0.45465797,  0.9999268 , ...,  0.9999834 ,
        -0.63596946,  0.9933187 ],
       ...,
       [-0.7585416 ,  0.55910033,  0.9999681 , ...,  0.99998975,
        -0.80699444,  0.9975414 ],
       [-0.5506401 ,  0.42502692,  0.9997803 , ...,  0.9999498 ,
        -0.667447  ,  0.989012  ],
       [-0.64506775,  0.40454087,  0.99986434, ...,  0.99997294,
        -0.6710821 ,  0.9959286 ]], dtype=float32)

In [ ]:
early_stopping = EarlyStopping(patience=10, monitor='val_loss', mode='min')

model.fit(bert_results['pooled_output'], y_train, epochs=200, batch_size=45)

Epoch 1/200
13/19 [===================>..........] - ETA: 0s

ValueError: Unexpected result of `train_function` (Empty logs). This could be due to issues in input pipeline that resulted in an empty dataset. Otherwise, please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.